package edu.antevortadb.dbInteraction.columnsAndKeys

import edu.antevortadb.configs.Finals

object TMDBMovies{
    fun csvKeys() = listOf(
            "budget",
            "genres",
            "homepage",
            "id",
            "keywords",
            "original_language",
            "original_title",
            "overview",
            "popularity",
            "production_companies",
            "production_countries",
            "release_date",
            "revenue",
            "runtime",
            "spoken_languages",
            "status",
            "tagline",
            "title",
            "vote_average",
            "vote_count"
    )

    fun columnNames() = listOf(
            Finals.ID,
            Finals.TMDB_ID,
            Finals.IMDB_ID,
            Finals.ML_ID,
            "budget",
            "tmdb_genres",
            "movielens_genres",
            "website",
            "keywords",
            "original_language",
            "original_title",
            "overview",
            "tmdb_popularity",
            "production_companies",
            "production_countries",
            "release_date",
            "revenue",
            "runtime",
            "spoken_languages",
            "released",
            "tagline",
            "tmdb_title",
            "movielens_title",
            "tmdb_vote_average",
            "tmdb_vote_count",
            "movielens_vote_average",
            "movielens_vote_count",
            "cast",
            "crew",
            "failure",
            "mild_success",
            "success",
            "great_success",
            "missing_data",
            "made_more_than_2x_budget",
            "performance_class"
    )

    fun columnsForPrinting() = columnNames()

    fun dataTypes() = listOf(
            " INTEGER PRIMARY KEY AUTOINCREMENT,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " JSON,",
            " JSON,",
            " TEXT,",
            " JSON,",
            " TEXT,",
            " TEXT,",
            " TEXT,",
            " REAL,",
            " JSON,",
            " JSON,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " JSON,",
            " INTEGER DEFAULT 0,",
            " TEXT,",
            " TEXT,",
            " TEXT,",
            " REAL,",
            " INTEGER,",
            " REAL,",
            " INTEGER,",
            " JSON,",
            " JSON,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER,",
            " INTEGER"
    )

    fun dataTypesForPrinting() = listOf(
            "INT",
            "INT",
            "INT",
            "INT",
            "INT",
            "JSON",
            "JSON",
            "TEXT",
            "JSON",
            "TEXT",
            "TEXT",
            "TEXT",
            "REAL",
            "JSON",
            "JSON",
            "INT",
            "INT",
            "INT",
            "JSON",
            "BOOL",
            "TEXT",
            "TEXT",
            "TEXT",
            "REAL",
            "INT",
            "REAL",
            "INT",
            "JSON",
            "JSON",
            "INT",
            "INT",
            "INT",
            "INT",
            "INT",
            "INT",
            "INT"
    )
}
